# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk chain generator using Rcpp
#' @description A random walk chain generator using Rcpp
#' @param sigma The value of variance
#' @param x0 the start point of the random walk chain
#' @param N repeat times
#' @return A list containing the random walk chain and the number
#' of accepeted times
#' @examples
#' \dontrun{
#' rw <- rwRcpp(2,15,10000)
#' rw$k
#' plot(rw$x,type='l')
#' }
#' @export
rwRcpp <- function(sigma, x0, N) {
    .Call('_StatComp20009_rwRcpp', PACKAGE = 'StatComp20009', sigma, x0, N)
}

